../src/pkg_system_mdr.sv
../src/TOP_bcd_7seg.sv
../src/pkg_bin_to_thto.sv
../src/displays.sv
../src/complement_a2.sv
../src/bin_to_thto.sv
../src/bin_to_7seg.sv
../src/add_con.sv
../src/add.sv
../src/square_root.sv
../src/shift_left.sv
../src/shift_left_quotient.sv
../src/shift_reg_right_data.sv
../src/root_op_calc.sv
../src/register.sv
../src/or_gate.sv
../src/mux_2powerN.sv
../src/multiplier_reg.sv
../src/demux_2powerN.sv
../src/and_gate.sv
../src/counter.sv
../src/pipo.sv
../src/mdr.sv
../src/control.sv
../src/multiplication.sv
../src/product_reg.sv
../src/shift_right_sign.sv
../src/multiplicand_reg.sv
../src/final_product.sv
../src/division.sv
../src/remainder_reg.sv
../src/sub.sv
../src/divisor_reg.sv
../src/quotation_reg.sv
../src/rem_full_reg.sv
../src/quotation_add.sv
../src/core.sv
../src/verification.sv
../src/selector_op.sv
../src/operation_mult.sv
../src/counter2.sv
../src/alu_mult.sv
../src/mux_2powerN2.sv
../src/mux_data.sv
../src/final_remainder.sv
../src/final_quotation.sv
../src/register_en.sv
../src/final_values.sv
../src/mux_output.sv
../src/clkDivider.sv
../src/sipo.sv
../src/verification2.sv
TB_mdr.sv

